title: "0x5E" # 网站标题
description: 0x5E 的个人博客 # 网站描述
keywords: ["0x5E", blog, hexo, 前端, 技术博客] # SEO 关键词
language: zh-CN # 语言
timezone: Asia/Shanghai # 时区
author: "0x5E" # 作者

url: https://bianyujie.cn # 你的站点地址（请保持和线上域名一致）
root: / # 子目录部署时改成 /子目录/

permalink: :title/ # 设置文章固定链接格式，这里为文章标题
permalink_defaults: # 固定链接的默认参数（如需特定设置可在此添加）

pretty_urls: # 美化 URL 配置
  trailing_index: true # 结尾是否保留 index.html，true 表示保留
  trailing_html: false # 结尾是否保留 .html 后缀，false 表示不保留

theme: brewski # 使用的主题

pagination_dir: page # 分页目录，如 page/2

index_generator:
  path: "" # 首页路径
  per_page: 10 # 首页每页显示文章数
  order_by: -date # 首页文章排序规则（-date 表示倒序，最新的文章排在前面）

archive_generator:
  per_page: 50 # 归档每页显示文章数
  yearly: true # 按年份归档
  monthly: false # 按月份归档

feed:
  type: rss2 # 订阅源类型，这里使用 RSS2 格式
  path: rss.xml # 生成的订阅源文件路径
  limit: 20 # 订阅源文章数限制，最多显示 20 篇
  content: true # 是否在订阅源中包含全文内容（true 为包含）

sitemap: # 站点地图配置
  path: sitemap.xml # 生成的站点地图文件路径
  tags: true # 是否包含标签页面
  categories: true # 是否包含分类页面
