name: "brewski" # 主题名称

menu: # 菜单配置
  首页: / # 首页链接
  归档: /archives # 归档页面链接
  关于: /about # 关于页面链接

favicon: /favicon.svg # 网站 favicon 图标路径
logo: /logo.svg # 网站 logo 图标路径

copyright: # 版权信息
  since: 2026 # 博客起始年份
  name: "0x5E" # 版权拥有者名称
  url: https://bianyujie.cn # 版权拥有者链接

giscus: # Giscus 评论系统配置
  enable: true # 是否启用 Giscus
  repo: devyujie/blog-commnts # GitHub 仓库 (格式: 用户名/仓库名)
  repo_id: R_kgDORK04Fg # 仓库 ID
  category: Announcements # 分类名称
  category_id: DIC_kwDORK04Fs4C2LoU # 分类 ID
  mapping: pathname # 用于定位评论线程的参数
  strict: '0' # 是否严格匹配
  reactions_enabled: '1' # 是否启用表情
  emit_metadata: '0' # 是否输出元数据
  input_position: top # 输入框位置
  theme: preferred_color_scheme # 主题
  lang: zh-CN # 语言
  loading: lazy # 加载方式

live2d: # 小宠物配置
  enable: false
  once: false # 是否仅在当前会话首次加载
  script: https://cdn.jsdelivr.net/npm/live2d-widget@3.1.4/lib/L2Dwidget.min.js
  model: https://cdn.jsdelivr.net/npm/live2d-widget-model-hijiki@1.0.5/assets/hijiki.model.json
  position: left
  width: 150
  height: 300
  hOffset: 20
  vOffset: -30
  mobile: false
  scale: 0.8
  opacityDefault: 0.7
  opacityOnHover: 0.2
